server:
  port: 8080  # 로컬 개발용 포트 설정, TODO: 서버 포트를 환경변수로 관리 (SERVER_PORT)

eureka:
  instance:
    prefer-ip-address: true  # IP 주소를 우선 사용하여 Eureka에 등록
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # TODO: Eureka 서버 URL을 환경변수로 관리 (EUREKA_URL)
    register-with-eureka: true

spring:
  main:
    web-application-type: reactive  # 리액티브 애플리케이션으로 설정
  application:
    name: api-gateway  # TODO: 애플리케이션 이름을 환경변수로 관리 (SPRING_APP_NAME)

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE  # user-service로 라우팅
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /${segment}  # 프리픽스 제거하고 내부 서비스로 전달

        - id: gallery-service
          uri: lb://GALLERY-SERVICE
          predicates:
            - Path=/gallery-service/**  # gallery-service 경로 필터 적용
          filters:
            - RewritePath=/gallery-service/(?<segment>.*), /${segment}  # 프리픽스 제거하고 내부 서비스로 전달

        - id: battle-service
          uri: lb://BATTLE-SERVICE
          predicates:
            - Path=/battle-service/**  # battle-service 경로 필터 적용
          filters:
            - RewritePath=/battle-service(?<segment>/.*),${segment}  # /battle-service 프리픽스 제거하고 나머지 유지

        # Swagger 통합 경로 설정
        - id: user-service-api-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs/**  # user-service의 API 문서 경로

        - id: gallery-service-api-docs
          uri: lb://GALLERY-SERVICE
          predicates:
            - Path=/gallery-service/v3/api-docs/**  # gallery-service의 API 문서 경로

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    enabled: true  # API 문서 활성화
  swagger-ui:
    enabled: true  # Swagger UI 활성화
    path: /swagger-ui/index.html  # Gateway를 통한 Swagger UI 접근 경로 설정
    url: /v3/api-docs  # Gateway에서 모든 서비스의 API를 통합하는 경로
    urls:
      - name: user-service
        url: /user-service/v3/api-docs  # user-service 문서 경로
      - name: gallery-service
        url: /gallery-service/v3/api-docs  # gallery-service 문서 경로

jwt:
  secret: e13af114d471424d6c9f2b7d03c3e25e630f269fbb3587f35068cb7d253150f568812b114afd8fd6941a005cdcf64b8b8baec4ce9de512b6aaad9ba732c6eee4  # TODO: JWT 비밀 키를 환경변수로 관리 (JWT_SECRET)
  expiration: 1296000000  # JWT 만료 시간, TODO: JWT 만료 시간을 환경변수로 관리 (JWT_EXPIRATION)

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework: DEBUG
