server:
  port: 8080  # 로컬 개발용 포트 설정

#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: false  # 호스트 이름 사용
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true

eureka:
  instance:
    prefer-ip-address: true  # IP 주소를 우선 사용하여 Eureka에 등록
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

spring:
  main:
    web-application-type: reactive  # 리액티브 애플리케이션으로 설정
  application:
    name: api-gateway

  cloud:
    gateway:
#      default-filters:
#        - PreserveHostHeader=true  # 호스트 헤더를 유지
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**  # user-service 경로 필터 적용
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}
#            - AddRequestHeader=Authorization, "Bearer #{JWT_TOKEN}"
#            - AddRequestHeader=X-User-ID, "#{USER_ID}"  # 사용자 ID 추가
#            - AddRequestHeader=X-User-Role, "#{USER_ROLE}"  # 사용자 역할 추가

        - id: gallery-service
          uri: lb://GALLERY-SERVICE
          predicates:
            - Path=/gallery-service/**  # gallery-service 경로 필터 적용
          filters:
            - RewritePath=/gallery-service/(?<path>.*), /$\{path}
#            - AddRequestHeader=Authorization, "Bearer #{JWT_TOKEN}"
#            - AddRequestHeader=X-User-ID, "#{USER_ID}"  # 사용자 ID 추가
#            - AddRequestHeader=X-User-Role, "#{USER_ROLE}"  # 사용자 역할 추가

        # Swagger 통합 경로 설정
        - id: user-service-api-docs
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs/**  # user-service의 API 문서 경로
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}

        - id: gallery-service-api-docs
          uri: lb://GALLERY-SERVICE
          predicates:
            - Path=/gallery-service/v3/api-docs/**  # gallery-service의 API 문서 경로
#          filters:
#            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    enabled: true  # API 문서 활성화
  swagger-ui:

    enabled: true  # Swagger UI 활성화
    path: /swagger-ui/index.html  # Gateway를 통한 Swagger UI 접근 경로 설정
    url: /v3/api-docs  # Gateway에서 모든 서비스의 API를 통합하는 경로
    urls:
      - name: user-service
        url: /user-service/v3/api-docs  # user-service 문서 경로
      - name: gallery-service
        url: /gallery-service/v3/api-docs  # gallery-service 문서 경로
jwt:
  secret: e13af114d471424d6c9f2b7d03c3e25e630f269fbb3587f35068cb7d253150f568812b114afd8fd6941a005cdcf64b8b8baec4ce9de512b6aaad9ba732c6eee4  # JWT 비밀 키
  expiration: 1296000000  # JWT 만료 시간

#logging:
#  level:
#    org.springframework.security: DEBUG
#    org.springframework: DEBUG
