server:
  port: 8082

spring:
  application:
    name: battle-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/battle_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 0oTd!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true

  kafka:
    bootstrap-servers: kafka1:9092  # Kafka 서버 주소

    template:
      # Producer topics
      from-battle-to-user: from_battle_to_user
      from-battle-to-gallery: from_battle_to_gallery

      # Consumer topics
      from-user-to-battle: from_user_to_battle
      from-gallery-to-battle: from_gallery_to_battle

    consumer:
      # Consumer group
      group-battle: battle

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: BattleScheduler
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
          threadPool:
            threadCount: 5

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false  # 호스트 이름 사용
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
