{
  "formatVersion": "1.1",
  "component": {
    "group": "com.threeheads",
    "module": "common-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "url": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "size": 27551,
          "sha512": "20132c3178ae9170df2b2217e8c868e12bc8aad59a639f06bdabad0d946dc1a3f718c7c3d0dd2942607d955db895d77e20ded040248c423bb22f94c3bbdc01bc",
          "sha256": "bf16dd7164878bc65b5fd570d8100cfd30e914f40764f77506143440aaabfab8",
          "sha1": "4eeb96f731e8874225c0e9a7e705ecbfe56c9e85",
          "md5": "d7e98a62e1afa20c0462b75c72372e79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "url": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "size": 27551,
          "sha512": "20132c3178ae9170df2b2217e8c868e12bc8aad59a639f06bdabad0d946dc1a3f718c7c3d0dd2942607d955db895d77e20ded040248c423bb22f94c3bbdc01bc",
          "sha256": "bf16dd7164878bc65b5fd570d8100cfd30e914f40764f77506143440aaabfab8",
          "sha1": "4eeb96f731e8874225c0e9a7e705ecbfe56c9e85",
          "md5": "d7e98a62e1afa20c0462b75c72372e79"
        }
      ]
    }
  ]
}
