{
  "formatVersion": "1.1",
  "component": {
    "group": "com.threeheads",
    "module": "common-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "url": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "size": 28507,
          "sha512": "f7e1099a797b7385176e7bdb849bdb00952916e1fc320a13c7502cfe9a27d1440a6b7952dfeb7b333ba012b5b2178866f1926761dfecab4a1621b1eeb72fa4b8",
          "sha256": "2946c6190eb57ce12e0c0db07a1033c6411188b6696f6ce8855c3d8a5ef24eb6",
          "sha1": "7d113f62d9bb93393807cf6db901b816daf1a770",
          "md5": "fea530fa7558a9771b9ad3076a833a47"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "url": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "size": 28507,
          "sha512": "f7e1099a797b7385176e7bdb849bdb00952916e1fc320a13c7502cfe9a27d1440a6b7952dfeb7b333ba012b5b2178866f1926761dfecab4a1621b1eeb72fa4b8",
          "sha256": "2946c6190eb57ce12e0c0db07a1033c6411188b6696f6ce8855c3d8a5ef24eb6",
          "sha1": "7d113f62d9bb93393807cf6db901b816daf1a770",
          "md5": "fea530fa7558a9771b9ad3076a833a47"
        }
      ]
    }
  ]
}
