{
  "formatVersion": "1.1",
  "component": {
    "group": "com.threeheads",
    "module": "common-library",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "url": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "size": 30452,
          "sha512": "75b588d2db24955a7966df653b5a0487a10bada028be8d6f2e2c13039ccd83fec14260043d99233d6d698a13fd0e3eff8ab8106d4b70b2019191c553f4ea63a8",
          "sha256": "04614cb908a9136d67658207c01cd4070856ffc19ef0d8ce894c167fac622d7b",
          "sha1": "d3613921f50ea241285a4ca50de1983276527ce2",
          "md5": "d8a7c5503663ba8e61006c28ab6e01b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-impl",
          "version": {
            "requires": "0.11.5"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-jackson",
          "version": {
            "requires": "0.11.5"
          }
        }
      ],
      "files": [
        {
          "name": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "url": "common-library-0.0.1-SNAPSHOT-plain.jar",
          "size": 30452,
          "sha512": "75b588d2db24955a7966df653b5a0487a10bada028be8d6f2e2c13039ccd83fec14260043d99233d6d698a13fd0e3eff8ab8106d4b70b2019191c553f4ea63a8",
          "sha256": "04614cb908a9136d67658207c01cd4070856ffc19ef0d8ce894c167fac622d7b",
          "sha1": "d3613921f50ea241285a4ca50de1983276527ce2",
          "md5": "d8a7c5503663ba8e61006c28ab6e01b9"
        }
      ]
    }
  ]
}
