version: "3.8"

services:
  redis:
    image: redis:latest
    command: redis-server --requirepass ootd201104
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - ootd-gateway-network  # 네트워크 설정 추가
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "ootd201104", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  ootd-gateway-network:
    driver: bridge
