spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root  # TODO: DB 사용자 이름을 환경변수로 관리 (DB_USERNAME)
    password: 0oTd!  # TODO: DB 비밀번호를 환경변수로 관리 (DB_PASSWORD)

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create  # TODO: 운영 환경에서는 'none'으로 변경
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true

  data:
    redis:
      host: localhost  # TODO: Redis 호스트를 환경변수로 관리 (REDIS_HOST)
      port: 6379  # TODO: Redis 포트를 환경변수로 관리 (REDIS_PORT)
      password: ootd201104  # TODO: Redis 비밀번호를 환경변수로 관리 (REDIS_PASSWORD)

  profiles:
    active: oauth  # 활성화할 Spring 프로파일 설정

  kafka:
    bootstrap-servers: kafka1:9092  # TODO: Kafka 서버 설정을 환경변수로 관리 (KAFKA_SERVERS)

    template:
      # Producer topics
      from-user-to-battle: from_user_to_battle
      from-user-to-gallery: from_user_to_gallery

      # Consumer topics
      from-battle-to-user: from_battle_to_user
      from-gallery-to-user: from_gallery_to_user

    consumer:
      # Consumer group
      group-user: user

eureka:
  instance:
    prefer-ip-address: true  # IP 주소를 우선 사용하여 Eureka에 등록
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # TODO: 유레카 서버 주소를 환경변수로 관리 (EUREKA_URL)
    register-with-eureka: true
    fetch-registry: true

server:
  port: 0  # TODO: 서버 포트를 환경변수로 관리 (SERVER_PORT)

#logging:
#  level:
#    org.springframework.security: DEBUG

jwt:
  secret: e13af114d471424d6c9f2b7d03c3e25e630f269fbb3587f35068cb7d253150f568812b114afd8fd6941a005cdcf64b8b8baec4ce9de512b6aaad9ba732c6eee4  # TODO: JWT 비밀 키를 환경변수로 관리 (JWT_SECRET)
  expiration: 1296000000  # JWT 만료 시간
