spring:
  kafka:
    template:
      # Producer topics
      from-user-to-battle: from_user_to_battle
      from-user-to-gallery: from_user_to_gallery

      # Consumer topics
      from-battle-to-user: from_battle_to_user
      from-gallery-to-user: from_gallery_to_user

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: fb7d24f77e374b62fe33b066aac83003  # TODO: 카카오 client-id를 환경변수로 관리 (KAKAO_CLIENT_ID)
            client-secret: 6a154q9xQ0z64nIJBhVzSIoIBXaa5Drb  # TODO: 카카오 client-secret을 환경변수로 관리 (KAKAO_CLIENT_SECRET)
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao  # TODO: redirect-uri를 환경변수로 관리 (KAKAO_REDIRECT_URI)
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
              - talk_message
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize  # TODO: authorization-uri를 환경변수로 관리 (KAKAO_AUTHORIZATION_URI)
            token-uri: https://kauth.kakao.com/oauth/token  # TODO: token-uri를 환경변수로 관리 (KAKAO_TOKEN_URI)
            user-info-uri: https://kapi.kakao.com/v2/user/me  # TODO: user-info-uri를 환경변수로 관리 (KAKAO_USER_INFO_URI)
            user-name-attribute: id
