services:
  gallery_db:
      image: mysql:8.0
      container_name: ootd-gallery-mysql
      environment:
        MYSQL_ROOT_PASSWORD: 0oTd!
        MYSQL_DATABASE: ootd
      volumes:
        # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        - ootd_gallery_mysql_data:/var/lib/mysql
      ports:
        - "3307:3306"
      networks:
        - ootd-gallery-Network
        
  gallery_backend:
    image: ohuggy/ootd-be-gallery
    container_name: ootd-be-gallery
    ports:
      - "8082:8080"
    depends_on:
      - gallery_db
    networks:
      - ootd-gallery-Network

volumes:
  ootd_gallery_mysql_data:

networks:
  ootd-gallery-Network:
    driver: bridge
