version: "3.8"

services:
  gallery_db:
    image: mysql:8.0
    container_name: gallery_db_container  # 직접 하드코딩
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ootd_gallery_mysql_data:/var/lib/mysql
    ports:
      - "${GALLERY_DB_PORT}:3306"
    networks:
      - ootd-gallery-network

volumes:
  ootd_gallery_mysql_data:

networks:
  ootd-gallery-network:
    driver: bridge
